csv_file_storage/csv_file_storage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('storage/', include('storage_app.urls')),
    path('auth/', include('myauth.urls')),
]

csv_file_storage/myauth/urls.py
from django.urls import path

from .views import LoginUser, logout_user, RegisterUser

app_name = 'myauth'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

csv_file_storage/storage_app/urls.py
from django.urls import path

from .views import Home, FileDetail, AddFile, DeleteFile

app_name = 'storage_app'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('file/<int:pk>/', FileDetail.as_view(), name="file_detail"),
    path('file/add/', AddFile.as_view(), name="add_file"),
    path('file/delete/<int:pk>/', DeleteFile.as_view(), name="delete_file"),
]

csv_file_storage/storage_app/models.py
import re

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
import os

from django.urls import reverse


def csv_file_directory_path(instance: "CSV_file", filename: str) -> str:
    """
    Функция для написания пити для хранения файла пользователя
    """
    return "user_{pk}/files/{filename}".format(
        pk=instance.owner.pk,
        filename=filename
    )

class CSV_file(models.Model):
    """
    Django модель, которая представляет собой загружаемый файл пользователя

    owner: владелец файла
    file: сам файл
    created_at: время загрузки файла
    """
    class Meta:
        ordering = ['pk']
        verbose_name_plural = 'CSV_files'
        verbose_name = "CSV_file"

    owner = models.ForeignKey(User, on_delete=models.PROTECT, related_name='files', verbose_name="Владелец")
    file = models.FileField(null=True, upload_to=csv_file_directory_path, verbose_name='Файл')
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('storage_app:file_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.file.name.split(os.path.sep)[-1]

    def clean(self):
        pattern = re.compile(r'.*\.csv$')

        if not pattern.search(self.file.name):
            raise ValidationError('Only .csv files are accepted')

csv_file_storage/storage_app/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError


def validate_file(file):
    """
    Валидатор, который проверяет, что загружаемый файл имеет расширение .csv
    """
    pattern = re.compile(r'.*\.csv$')

    if not pattern.search(file.name):
        raise ValidationError('Для загрузки доступны только .csv файлы')


class AddFileForm(forms.Form):
    """
    Django форма для добавления файла csv
    """
    file = forms.FileField(label='Файл', validators=[validate_file])

csv_file_storage/storage_app/views.py
import csv

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.core.paginator import Paginator

from .models import CSV_file
from .forms import AddFileForm

menu = [{'title': "Главная страница", 'url_name': 'storage_app:home'},
        {'title': "Добавить новый файл", 'url_name': 'storage_app:add_file'},
        ]


class Home(ListView):
    """
    View, которая выводит на страницу список загруженных пользователями файлов.
    У каждого файла отображается имя владельца, дата загрузки, название и список заголовков.
    """
    model = CSV_file
    template_name = 'storage_app/index.html'
    context_object_name = 'files'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = menu
        context['title'] = 'Главная страница'
        return context


class FileDetail(DetailView):
    """
    View для вывода содержимого csv файла
    """
    model = CSV_file
    template_name = 'storage_app/file_detail.html'
    context_object_name = 'file'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        rows = self.get_rows()
        paginator = Paginator(rows, 15)

        page_number = self.request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context['menu'] = menu
        context['title'] = 'Информация о файле'
        context['page_obj'] = page_obj
        context['paginator'] = paginator
        return context

    def get_rows(self):
        path = self.object.file.path
        with open(path) as csvfile:
            reader = csv.reader(csvfile)
            next(reader)
            rows = [row for row in reader]

        return rows


class AddFile(LoginRequiredMixin, View):
    """
    View для добавления нового csv файла
    """

    def get(self, request: HttpRequest):
        form = AddFileForm()
        context = {
            'title': 'Загрузка нового файла',
            'menu': menu,
            'form': form,
        }
        return render(request, 'storage_app/add_file.html', context=context)

    def post(self, request: HttpRequest):
        form = AddFileForm(request.POST, request.FILES)
        if form.is_valid():
            owner = request.user
            form.cleaned_data['owner'] = owner
            file = CSV_file.objects.create(**form.cleaned_data)
            return redirect(file.get_absolute_url())

        context = {
            'title': 'Загрузка нового файла',
            'menu': menu,
            'form': form,
        }
        return render(request, 'storage_app/add_file.html', context=context)


class DeleteFile(DeleteView):
    """
    View для удаления csv файла пользователя
    """
    model = CSV_file
    context_object_name = 'file'
    success_url = reverse_lazy("storage_app:home")
    template_name = 'storage_app/delete_file.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление файла'
        context['menu'] = menu
        return context

csv_file_storage/storage_app/templates/storage_app/add_file.html
{% extends 'storage_app/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form action="{% url 'storage_app:add_file' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}

  <div class="form-error">{{ form.non_field_errors }}</div>

  {% for f in form %}
  <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
  <div class="form-error">{{ f.errors }}</div>
  {% endfor %}


  <button class="btn" type="submit">Добавить</button>
</form>

{% endblock %}

csv_file_storage/storage_app/templates/storage_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{{title}}</title>
  <link type="text/css" href="{% static 'storage_app/css/styles.css' %}" rel="stylesheet"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="shortcut icon" href="{% static 'storage_app/images/main.ico' %}" type="image/x-icon"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block style %}
  {% endblock %}
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
  <tr>
    <td valign=top>
      {% block mainmenu %}
      <div class="header">
        <ul id="mainmenu" class="mainmenu">
          <li class="logo"><a href="{% url 'storage_app:home' %}">
            <div class="logo"></div>
          </a></li>
          {% for m in menu %}
          <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
          {% endfor %}
          {% if request.user.is_authenticated %}
          <li class="last"> {{user.username}} | <a href="{% url 'myauth:logout' %}">Выйти</a></li>
          {% else %}
          <li class="last"><a href="{% url 'myauth:register' %}">Регистрация</a> | <a href="{% url 'myauth:login' %}">Войти</a>
          </li>
          {% endif %}
        </ul>
        <div class="clear"></div>
      </div>
      {% endblock mainmenu %}


      <table class="table-content" border=0 cellpadding="0" cellspacing="0">
        <tr>
          <!-- Sidebar слева -->
          <td valign="top" class="left-chapters">
            <ul id="leftchapters">
              <li class="share">
                <p>Мой телеграмм</p>
                <a class="share-yt" href="https://t.me/In_valiDen" target="_blank" rel="nofollow"></a>
              </li>
            </ul>
          </td>
          <!-- Конец Sidebar'а -->
          <td valign="top" class="content">
            <!-- Хлебные крошки -->
            {% block breadcrumbs %}
            {% endblock %}

            <!-- Блок контента -->
            <div class="content-text">
              {% block content %}
              {% endblock %}
              {% if page_obj.has_other_pages %}
              <nav class="list-pages">
                <ul>
                  {% if page_obj.has_previous %}
                  <li class="page-num">
                    <a href="?page={{ page_obj.previous_page_number }}&">&lt;</a>
                  </li>
                  {% endif %}

                  {% for p in paginator.page_range %}
                  {% if page_obj.number == p %}
                  <li class="page-num page-num-selected">{{ p }}</li>
                  {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                  <li class="page-num">
                    <a href="?page={{ p }}&">{{ p }}</a>
                  </li>
                  {% endif %}
                  {% endfor %}

                  {% if page_obj.has_next %}
                  <li class="page-num">
                    <a href="?page={{ page_obj.next_page_number }}&">&gt;</a>
                  </li>
                  {% endif %}

                </ul>
              </nav>
              {% endif %}
            </div>
            <!-- Конец блока контента -->

          </td>
        </tr>
      </table>
    </td>
  </tr>
  <!-- Footer -->
  <tr>
    <td valign=top>
      <div id="footer">
        <p>&copy; 2023 Частичное или полное копирование информации с данного сайта для распространения на других
          ресурсах, в том числе и бумажных, строго не запрещено.</p>
      </div>
    </td>
  </tr>
</table>
<!-- Конец footer'а и страницы -->
</body>
</html>

csv_file_storage/storage_app/templates/storage_app/delete_file.html
{% extends 'storage_app/base.html' %}

{% block content %}
<div class="center">
  <form method="post" class="card">
    {% csrf_token %}
    <h2>Удаление файла</h2>
    <p>Вы уверены, что хотите удалить файл "{{ file }}"?</p>
    <p class="link-read-post">
      <input type="submit" value="Удалить">
      <a href="{{ file.get_absolute_url }}">Отмена</a>
    </p>
  </form>
</div>
{% endblock %}

csv_file_storage/storage_app/templates/storage_app/file_detail.html
{% extends 'storage_app/base.html' %}
{% load mytag %}
{% load static %}


{% block style %}
<style>
  .price-list {
      border: 1px solid gray;
      border-collapse: collapse;
  }

  .price-list td, .price-list th {
      border: 1px solid gray;
      padding: 5px;
  }

  .price-list thead {
      background-color: lightgray;
  }
</style>
{% endblock %}


{% block content %}
<h1>{{ file }}</h1>
{% if user.is_authenticated %}
{% if file.owner == user %}
<p class="link-read-post"><a href="{% url 'storage_app:delete_file' file.id %}">Удалить файл</a></p>
{% endif %}
{% endif %}
{% get_headers path=file.file.path as headers %}
<table class="price-list">
  <thead>
  <tr>
    {% for head in headers %}
    <th>{{ head }}</th>
    {% endfor %}
  </tr>
  </thead>
  <tbody>
  {% for row in page_obj.object_list %}
  <tr>
    {% for elem in row %}
    <td>{{ elem }}</td>
    {% endfor %}
  </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

csv_file_storage/storage_app/templates/storage_app/index.html
{% extends 'storage_app/base.html' %}
{% load mytag %}

{% block content %}
<ul class="list-articles">
  {% if not files %}
  <li>No files yet</li>
  {% else %}
  {% for file in files %}
  <li>
    <div class="article-panel">
      <p class="first">Загрузил: {{file.owner.username}}</p>
      <p class="last">Дата загрузки: {{file.created_at|date:"d-m-Y H:i:s"}}</p>
    </div>
    <h2>{{file}}</h2>
    {% get_headers path=file.file.path as headers %}
    <ul>
      {% for head in headers|slice:"6" %}
      <li>{{ head }}</li>
      {% endfor %}
      {% if headers|length > 6 %}
      <li>...</li>
      {% endif %}
    </ul>
    <div class="clear"></div>
    <p class="link-read-post"><a href="{{ file.get_absolute_url }}">Посмотреть файл</a></p>
  </li>
  {% endfor %}
  {% endif %}
</ul>
{% endblock %}

csv_file_storage/storage_app/templates/storage_app/login.html
{% extends 'storage_app/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

<div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Войти</button>
</form>

{% endblock %}

csv_file_storage/storage_app/templates/storage_app/register.html
{% extends 'storage_app/base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Регистрация</button>
</form>

{% endblock %}